apiVersion: v1
kind: Service
metadata:
  name: millicent-deployment-service
spec:
  selector:
    app: millicent
    object: millicent-app-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
status: