apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: mysql
    pod: mysql-pod
  name: mysql-pod
spec:
  containers:
  - image: mysql:latest
    name: mysql-pod
    env:
    - name: MYSQL_ROOT_USER
      valueFrom:
        secretKeyRef:
          name: mysql-secret
          key: user
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-secret
          key: password
    ports: 
    - name: mysql
      containerPort: 3306
      protocol: TCP 
    volumeMounts:
    - name: k8s-mysql-volume
      mountPath: /var/lib/mysql
  volumes:
  - name: k8s-mysql-volume
    emptyDir: {}