apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: millicent-cronjob
spec:
  schedule: "0 22 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: millicent-cronjob-container
            image: buildpack-deps:curl
            args:
            - /bin/sh
            - -ec 
            - curl http://gregory.solutions/getWebHits?fake-api-key-x=qQVO8StCP6v4vGMQ3LYz
            # @TODO: add JWT to application
          restartPolicy: Never